### ISSUE TITLE
Roadmap: Merging all Client apps into a single project

### ISSUE THREAD

**Issue by spaenleh** [graasp/graasp-account#380]
We would like to reduce the spread of the project to have to maintain and work on a single app for the client.

- [ ] move to `pnpm` for package management: lighter and faster than `yarn` and also supports workspaces (will be useful in the future maybe)
- [ ] use `@tanstack/react-router` instead of `react-router-dom` as it allows to split on routes and managing routes with typesafety is awesome
- [ ] migrate account to tanstack router
  - keep redirections to auth.graasp.org
- [ ] migrate the landing page here
- [ ] deploy to `graasp.org` instead of `account.graasp.org`
  - [ ] landing page should be multilingual
  - [ ] try to include prerendering with vinxi (see tanstack start configuration)
- [ ] `graasp.org` should hit the load-balancer and direct queries to `/api` to the backend
- [ ] query-client can be moved to single origin (no need to specify the `API_HOST` anymore, just use relative routes)
- [ ] migrate player here
- [ ] migrate builder here
- [ ] `builder.graasp.org`, `auth.graasp.org`, `player.graasp.org` should redirect to the path equivalents using the load-balancer

**Comment by pyphilia** [comment]
What's the difference between "use @tanstack/react-router" and "migrate account to tanstack router". Are you referring to the code, then to the deployment?

Otherwise seems like a good plan!
